name: OWASP Security Pipeline

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  actions: read

jobs:
  dependency_check:
    name: SCA - OWASP Dependency-Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Crear carpeta de reportes
        run: mkdir -p reports/dependency-check

      - name: Run Dependency-Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: 'mi-proyecto'
          path: '.'
          format: 'HTML'
          out: 'reports/dependency-check'
          args: >
            --noupdate

      - name: Ver archivos generados por Dependency-Check
        if: always()
        run: |
          echo "Contenido de reports:"
          ls -R reports || true

      - name: Subir reporte Dependency-Check
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: reports/dependency-check

  zap_baseline:
    name: DAST - OWASP ZAP Baseline
    runs-on: ubuntu-latest
    needs: dependency_check

    steps:
      - name: Run ZAP Baseline
        uses: zaproxy/action-baseline@v0.12.0
        with:
          target: 'https://tusitio.com'
          fail_action: false
          cmd_options: '-a -r report_html.html -w report_md.md -J report_json.json'

      - name: Ver archivos generados por ZAP
        if: always()
        run: |
          echo "Root:"
          ls -la
          echo "Buscar reportes:"
          find . -maxdepth 2 -type f | sort

      - name: Subir reporte ZAP HTML
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: zap-html-report
          path: report_html.html

      - name: Subir reporte ZAP Markdown
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: zap-md-report
          path: report_md.md

      - name: Subir reporte ZAP JSON
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: zap-json-report
          path: report_json.json
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: zap-baseline-report
          path: reports/zap
